### ISSUE TITLE
router.run never resolves

### ISSUE THREAD

**Issue by captainill** [esnunes/restaurants#2]
Thanks for sharing this example. I'm having trouble running this locally, however. The app just hangs and never renders. I believe I've traced the issues to the `router.run` callback never resolving. I can't figure out what the issue is. Any ideas?

**Comment by esnunes** [comment]
Hi @captainill , thanks for the feedback, it was a mistake on the environment variable pointing to the POI service.
To run it locally please run:

``` bash
POI_SERVICE_URL=http://poi-service.enunes.com npm start
```

Thanks and sorry about that!
